#!/bin/bash

if [ $# -lt 1 ]; then
  echo 'Usage: clang-target-x64 <TARGET> [<AR NAME> [<LD name>]]'
  exit
fi

export CXXFLAGS=${CXXFLAGS}\ "-nostdlib -nostdinc -ffreestanding -mno-red-zone -fno-exceptions -fno-rtti -Wno-long-long -Wall -Wextra -std=c++11 -mno-sse -mno-mmx -fno-stack-protector -fno-builtin -integrated-as -target x86_64-pc-none-elf64 -mcmodel=large"
export CFLAGS=${CFLAGS}\ "-nostdlib -nostdinc -ffreestanding -mno-red-zone -Wno-long-long -Wall -Wextra -mno-sse -mno-mmx -fno-stack-protector -fno-builtin -integrated-as -target x86_64-pc-none-elf64 -mcmodel=large"

if [ $# -gt 1 ]; then
  export AR=$2
fi

if [ $# -gt 2 ]; then
  export LD=$3
fi

make clean && make $1
