#!/bin/bash

if [ $# != 3 ]; then
  echo 'Usage: clang-target-x64 <TARGET> <LD NAME> <AR name>'
  exit
fi

export CXXFLAGS=${CXXFLAGS}\ "-nostdlib -nostdinc -ffreestanding -mno-red-zone -fno-exceptions -fno-rtti -Wno-long-long -Wall -Wextra -std=c++11 -mno-sse -mno-mmx -fno-stack-protector -fno-builtin -integrated-as -target x86_64-pc-none-elf64 -mcmodel=large"
export CFLAGS=${CFLAGS}\ "-nostdlib -nostdinc -ffreestanding -mno-red-zone -Wno-long-long -Wall -Wextra -mno-sse -mno-mmx -fno-stack-protector -fno-builtin -integrated-as -target x86_64-pc-none-elf64 -mcmodel=large"
export LD=$2
export AR=$3

make clean && make $1
